### ISSUE TITLE
YT Video is private

### ISSUE THREAD

**Issue by CheeksTheGeek** [hkirat/react-assignment#1]
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/39400946/232314128-e91143bc-d4fe-4cd6-a555-cf1bf4f870b8.png">

**Comment by Bhakti087** [comment]
Its working

**Comment by CheeksTheGeek** [comment]
it seems like the video was private for the time being, and now he changed the visibility, hence I'll close this issue!

**Comment by Bhakti087** [comment]
Yeah right
